### ISSUE TITLE
[BUG] XP not updating after teleport

### ISSUE THREAD

**Issue by xdjzack** [LordDeatHunter/FabricWaystones#105]
Minecraft 1.18.1 on fabric-api-0.46.6+1.18.jar

Using Fabric Waystones version (wraith-waystones-2.4.1.jar)

When teleporting, the xp does not update.
Only updates when recieving new xp or after a relog.

Before teleport
![Before teleport](https://user-images.githubusercontent.com/68829496/159147798-06cfaebf-d156-46a2-8cb7-9a1a7f9a131f.PNG)

After Teleport - Still lvl 4
![After Teleport - Still lvl 4](https://user-images.githubusercontent.com/68829496/159147799-efeaa1c5-b22d-47ed-b3f2-aff568430362.PNG)

Updates after one bottle of xp
![Updates after one bottle of xp](https://user-images.githubusercontent.com/68829496/159147804-596c30e8-7c42-4c99-8a00-a37081973d61.PNG)

**Comment by LordDeatHunter** [comment]
Vanilla bug, should be fixed in latest (2.5.0), reopen if not.

**Comment by xdjzack** [comment]
I'm playing on 1.18.1
(2.5.0) is for 1.18.2

**Comment by LordDeatHunter** [comment]
I mostly work on latest versions for updates, unless it is something very critical.

**Comment by xdjzack** [comment]
I will remove the cost then :)

**Comment by Slarper** [comment]
just use my fork version https://github.com/Slarper/FabricWaystones/releases/tag/2.4.1

**Comment by Slarper** [comment]
I move it to https://github.com/Slarper/Slarper-FabricWaystones/releases/tag/v2.4.2
