### ISSUE TITLE
[1.16.3] Crash with 1.0.9 

### ISSUE THREAD

**Issue by cybercat5555** [LordDeatHunter/FabricWaystones#11]
The game crashes before its outside of the loading screen with this build. Crash log:
[crash-2020-11-03_09.35.57-client.txt](https://github.com/LordDeatHunter/FabricWaystones/files/5481900/crash-2020-11-03_09.35.57-client.txt)

**Comment by LordDeatHunter** [comment]
Should be fixed by updating FabricAPI.
