### ISSUE TITLE
advise to use the api method for better mod capability

### ISSUE THREAD

**Issue by Slarper** [LordDeatHunter/FabricWaystones#114]
#109 because I have a mod that inject the method `player.addExperienceLevels(-amount)` to avoid exp cost, but it doesn't affect the waystones, so I find the reason that waystones mod uses `player.experienceLevel -= amount;`. 

So I suggest that using the method `player.addExperienceLevels(-amount)` to replace it for better mod capability.

**Comment by Slarper** [comment]
If you think this is not a good suggestion, I will feel sorry and won't mention it again.

**Comment by LordDeatHunter** [comment]
Took a bit, but done 👍
(Also, not sure if you're doing the injection for waystones-only, but if so, you can disable the cost in the configs)

**Comment by Slarper** [comment]
Thank you! Actually I know how to disable the cost in the configs, but I still think that it deserves to make this modification.
