### ISSUE TITLE
[Bug Report] Levels disappearing when travelling between worlds.

### ISSUE THREAD

**Issue by BulletTide** [LordDeatHunter/FabricWaystones#12]
Levels seem to "reset" when traveling across worlds (eg. overworld to end). The levels don't actually completely reset, but seem to become stagnant and in return, doesn't display a level, thus not allowing you to re-use the waystone until you obtain another orb to have the levels re-appear again.

**Comment by TelepathicGrunt** [comment]
This is a vanilla bug actually. https://bugs.mojang.com/browse/MC-124177

**Comment by LordDeatHunter** [comment]
Fixed 👍
