### ISSUE TITLE
Disable Pocket Wormhole?

### ISSUE THREAD

**Issue by megacorvega** [LordDeatHunter/FabricWaystones#127]
Is there a way to disable the ability to craft the Pocket Wormhole? If not, is that something that can be added as an option to the config?

**Comment by LordDeatHunter** [comment]
Either use vanilla datapacks or something like CraftTweaker or KubeJS.

**Comment by SandWoodJones** [comment]
Could you add an option for keeping the Pocket Wormhole item but disabling the ability to teleport to waystones with it?

**Comment by LordDeatHunter** [comment]
What would be the point of the item existing if it doesn't do anything?

**Comment by SandWoodJones** [comment]
In my case I would use it for the crafting the waystones themselves and only allow the player to travel using the waystones.

**Comment by LordDeatHunter** [comment]
If you just want a blank item for crafting, you can make one with CraftTweaker or KubeJS.
