### ISSUE TITLE
Incompatible with Terralith and Towns & Towers?

### ISSUE THREAD

**Issue by Sinuce** [LordDeatHunter/FabricWaystones#128]
Fabric Waystones throws errors in server console at startup, when datapacks [Terralith](https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/) and [Towns & Towers](https://www.planetminecraft.com/data-pack/towns-amp-towers-structure-overhaul/) are enabled.

It does not seem to recognise the new village types.
Is this a bug, or am I doing something wrong in the config?

Running version "_wraith-waystones-3.0.0.jar_" for Minecraft 1.19.

> [22:04:18] [main/INFO]: Applied 2 biome modifications to 2 of 170 new biomes in 8.807 ms
> [22:04:18] [Server thread/INFO]: Adding waystone fwaystones:village_waystone to village minecraft:village/savanna/houses
> [22:04:18] [Server thread/INFO]: Adding waystone fwaystones:stone_brick_village_waystone to village towns_and_towers:village_birch_forest
> [22:04:18] [Server thread/ERROR]: Cannot add to towns_and_towers:village_birch_forest as it cannot be found!
> [22:04:18] [Server thread/INFO]: Adding waystone fwaystones:village_waystone to village terralith:fortified_village
> [22:04:18] [Server thread/ERROR]: Cannot add to terralith:fortified_village as it cannot be found!
> [22:04:18] [Server thread/INFO]: Adding waystone fwaystones:desert_village_waystone to village towns_and_towers:village_beach
> [22:04:18] [Server thread/ERROR]: Cannot add to towns_and_towers:village_beach as it cannot be found!
> [22:04:18] [Server thread/INFO]: Adding waystone fwaystones:village_waystone to village towns_and_towers:village_meadow
> [22:04:18] [Server thread/ERROR]: Cannot add to towns_and_towers:village_meadow as it cannot be found!
> [22:04:18] [Server thread/INFO]: Adding waystone fwaystones:village_waystone to village minecraft:village/taiga/houses
> [22:04:18] [Server thread/INFO]: Adding waystone fwaystones:nether_brick_village_waystone to village incendium:piglin_village
> [22:04:18] [Server thread/ERROR]: Cannot add to incendium:piglin_village as it cannot be found!
> [...]

My fwaystones config: [config-json.zip](https://github.com/LordDeatHunter/FabricWaystones/files/8894121/config-json.zip)

**Comment by LordDeatHunter** [comment]
Seems like you have the incorrect structure paths.
`terralith:village/fortified/houses`
`terralith:village/desert/houses`
etc. for Terralith
`kaisyn/village/birch_forest_romanian/houses`
etc. for T&T

**Comment by Dashing-Rana** [comment]
> Ah. Sorry, that was my bad. Thank you a ton for your quick and elaborate reply. Now I have learned how to fix it ❤️

Can i get you config file cause i have same datapacks and same problem 😥

**Comment by Sinuce** [comment]
Here you go @Dashing-Rana:
\.minecraft\config\fwaystones\[config-json.txt](https://github.com/LordDeatHunter/FabricWaystones/files/9027641/config-json.txt)
Just rename file to config.json

I also tried "incendium:castle/courtyards", but sadly that does not seem to work.

Good luck.

**Comment by Sinuce** [comment]
> Thanks i also have Choice Theorems Overhauled Villages! Any changes required for this reason?

¯\\_(ツ)_/¯
