### ISSUE TITLE
[Bug]: Inventory-Sorting cannot blacklist waystone GUI

### ISSUE THREAD

**Issue by SandWoodJones** [LordDeatHunter/FabricWaystones#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using the [Inventory-Sorting](https://www.curseforge.com/minecraft/mc-mods/inventory-sorting) mod, the sort button shows up in the waystone screen, the configure waystone screen, the abyss watcher screen and the pocket wormhole screen even though none of these screens have an inventory. For example: 
![image](https://user-images.githubusercontent.com/35671374/179682366-0ce36a21-b7ec-423b-abed-895f41acce0f.png)

Inventory-Sorting has a feature for these sorts of things that allows you to blacklist screens from showing the sort button. When trying to do this with this mod's screens however I get the following message:
`[inventorysorter]: Un-blacklistable screen, or screen is already blacklisted`

### To Reproduce

1. With fabric-waystones and inventory sorting installed
2. Enable inventory sorting's debug mode
3. Right-click a waystone
4. The sort button will be displayed
5. Ctrl+Click it to blacklist it
6. The above message will be displayed in chat

### Expected behavior

When blacklisting is successful the messages; 
![image](https://user-images.githubusercontent.com/35671374/179682719-786c9871-44e5-4e26-83d2-9ab86a8121a7.png)
are displayed.

### Mod Version

v2.5.0

### Minecraft Version

1.19

### Java Version

Java 18

### Fabric Version

- **Fabric:** 0.14.8
- **Fabric API:** 0.57.2

**Comment by LordDeatHunter** [comment]
I opened a [PR on their side](https://github.com/kyrptonaught/Inventory-Sorter/pull/93/files). For the time being, you can try manually changing the inventory sorter configs to include [the strings I added](https://github.com/kyrptonaught/Inventory-Sorter/pull/93/files).
![image](https://user-images.githubusercontent.com/26803198/223228044-8986c5cb-8c80-4e73-8a50-d14fdfc7cd14.png)
