### ISSUE TITLE
[BUG REPORT] Waystone is still active even though it is broken.

### ISSUE THREAD

**Issue by SPARDA-REQUIEM** [LordDeatHunter/FabricWaystones#14]
Hello, I have noticed that sometimes when I place a waystone to a location far away from my minecraft house, then teleport back to home, then teleport back again to the said location and break the waystone, it will not remove the waystone as I still can teleport from it when I use another waystone, even without the waystone placed there.

**Comment by LordDeatHunter** [comment]
Should be fixed. Can you test it?

**Comment by SPARDA-REQUIEM** [comment]
Hello, it's been a while since I played Minecraft with this mod again. Currently, the bug I had issued last year hasn't occurred to me, yet, and I will let you know when that happens again.
