### ISSUE TITLE
[Bug]: Waystones simply don't teleport you

### ISSUE THREAD

**Issue by Daktyl198** [LordDeatHunter/FabricWaystones#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Placing, configuring, and opening waystones works perfectly, but when actually attempting to travel using any waystone in the world, it fails. There's no log of any failure that I can see anywhere, and the debug tool only seems to show the NBT data of the waystone I click on, rather than logging anything.

### To Reproduce

1. Place down 2 waypoints, anywhere
2. Try using said waypoints
3. Nothing happens

### Expected behavior

Teleportation between the two waypoints.

### Mod Version

v2.5.0

### Minecraft Version

1.19

### Java Version

Java 17

### Fabric Version

Latest version of Fabric for 1.19

**Comment by LordDeatHunter** [comment]
Have you checked #140 and #134 ? It might be a similar issue.
Also, I would highly recommend updating to the latest version of the mod.

**Comment by Daktyl198** [comment]
Weird, I swear I searched before making this bug.
Turned out to be the same as #134. I installed VMP preemptively to help a player on my server who I know has bad internet, so I'm just going to run the server without it for now. With VMP disabled the waystones work perfectly.
