### ISSUE TITLE
[Bug]: Duplicate waystones that can't be forgotten

### ISSUE THREAD

**Issue by sparrowpaws** [LordDeatHunter/FabricWaystones#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When anyone opens a waystone, some names appear twice. When trying to forget either of the two duplicated names, they don't get removed, the list just appears to move up by one. Both names can be used to teleport to the waystone. You can still forget other waystones that are not duplicated. This happened after updating a few mods from the server to newer versions, but the Waystones mod was not changed.

### To Reproduce

The list of mods:
[modlistforserver.txt](https://github.com/LordDeatHunter/FabricWaystones/files/9301639/modlistforserver.txt)
(Waystones version 2.5.5)

Unsure of how to reproduce in singleplayer and don't have another server to reproduce on. 

### Expected behavior

Should be able to forget all waystones, and not have duplicated waystones appearing in the list.

### Mod Version

v2.5.5

### Minecraft Version

1.18.2

### Java Version

Java 17

### Fabric Version

- **Fabric Loader:** 0.14.8-1.18.2
- **Fabric API:** 0.58.0+1.18.2

### Anything else?

Here's an image of some of the duplicates. I can attach a video example if needed. ![2022-08-10_11 50 33](https://user-images.githubusercontent.com/94473307/183953203-81146255-5de2-4d1a-9d00-67700c3e21f5.png)

**Comment by LordDeatHunter** [comment]
Which mods were updated?

**Comment by sparrowpaws** [comment]
here's a ss of the mods that were updated to new versions ![modsthatwereupdated](https://user-images.githubusercontent.com/94473307/183996930-dcb22d2c-e2c6-4414-92a9-cebbc85d7dd2.jpg)

**Comment by bloodyeyesblackblood** [comment]
![image](https://github.com/LordDeatHunter/FabricWaystones/assets/108025342/2a800501-d264-48fb-98e9-9c405d90de46)
same here, happened after moving the files to another server or editing the config file?

searched for a file to delete the duplicates myself, but i can't find it? is there a "txt/json"? file where it gets saved to?

**Comment by LordDeatHunter** [comment]
@bloodyeyesblackblood you can check the wiki page for manual Waystone editing:
https://github.com/LordDeatHunter/FabricWaystones/wiki/Manual_Editing
As for the issue, I am aware of it, but haven't had any luck in reproducing it so far.

**Comment by bloodyeyesblackblood** [comment]
> @bloodyeyesblackblood you can check the [wiki page for manual Waystone editing.](https://github.com/LordDeatHunter/FabricWaystones/wiki/Manual_Editing) As for the issue, I am aware of it, but haven't had any luck in reproducing it so far.

thanks, i'll try to reproduce the things i did.

the nbt editor is a bit tricky, also the duplicates have a different hash.

[5](https://irath96.github.io/webNBT/#)

    [color: 13743503](https://irath96.github.io/webNBT/#)
    [dimension: "minecraft:overworld"](https://irath96.github.io/webNBT/#)
    [hash: "[17, 105, 99, -73, 112, -114, 26, -30, 96, 60, -73, -54, -59, -51, -102, 107, 61, 42, -78, -29, -44, -126, 62, -39, -121, 121, 114, 76, -76, -72, -110, -124]"](https://irath96.github.io/webNBT/#)
    [name: "BD -3480 ~ 86"](https://irath96.github.io/webNBT/#)
    [position 3 ints](https://irath96.github.io/webNBT/#)

[6](https://irath96.github.io/webNBT/#)

    [color: 13743503](https://irath96.github.io/webNBT/#)
    [dimension: "minecraft:overworld"](https://irath96.github.io/webNBT/#)
    [hash: "[-83, 98, -23, 22, 99, -93, -120, -27, -36, 94, 15, 120, -124, 116, -106, 111, 98, 15, -109, -8, -68, 108, 91, 122, -43, -96, 49, 112, -126, -109, -22, 32]"](https://irath96.github.io/webNBT/#)
    [name: "BD -3480 ~ 86"](https://irath96.github.io/webNBT/#)
    [position 3 ints](https://irath96.github.io/webNBT/#)

idk if it helps :)

**Comment by LordDeatHunter** [comment]
Well, kinda 🤔 The hashes aren't reversible, so I can't really check what's going on for sure. Given the same position (x, y, z coords) & dimension, it should always return the same hash.
The only exception I can think of is if ***somehow*** a single Waystone generates 2 hashes, 1 for the bottom block & 1 for the top block....

**Comment by LordDeatHunter** [comment]
Yikes, I see what's up with the hashes...
#225

**Comment by ST-DDT** [comment]
I encountered the same issue with the latest update:

- wraith-waystones-3.1.3+mc1.20 -> wraith-waystones-3.3.2+mc1.20.1
