### ISSUE TITLE
[Bug]: Scroll of Infinite Knowledge causes a huge Crash 3.0.4

### ISSUE THREAD

**Issue by Colur87** [LordDeatHunter/FabricWaystones#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When somone uses the Scroll of Infinite Knowledge, the server crash really hard, so hard that it changes the seed of the entire server. Every time you use it.

### To Reproduce

giv you the scroll of infinite knowlege right klick, and the server crashes, chances are 50/50 that you have a broken world with a other seed

### Expected behavior

Please Fix

### Mod Version

v2.5.0

### Minecraft Version

1.19

### Java Version

Java 17

### Fabric Version

Fabric Loader 0.14.9
fabric-api-0.62.0+1.19.2

**Comment by LordDeatHunter** [comment]
1. Please provide a crash log. Not much help can be given otherwise.
2. Looks like an issue that was already fixed, please update to the latest version of Fabric Waystones, and re-open the issue if it still persists.
