### ISSUE TITLE
[Bug]: Scrolls not showing, even after reconnecting, restarting server 

### ISSUE THREAD

**Issue by Rinerak** [LordDeatHunter/FabricWaystones#165]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### So, how it started...
**This only occurs on a multiplayer server**
Recently i was playing on a private server, that we have w my friends, and i had resources to make a few waystones. For few times it actually worked normally. Then the next day it started kinda glitching. So i went back to the waystones to find them again. That worked 2 times. After that it got to the state that it is in right now. Now, even after revisiting the waystones, i cant teleport on one or even see one in menu. I tried to even loading it with the waystone scrolls. I talked to the admins, that are my friends, and even they dont know, what to do with it.

_I tried to find something on google, but there wasn't anything about this bug_
Thanks beforehand:)

### To Reproduce

1. Play on a multiplayer server with this mod
2. Get to a first waystone
3. Get to other waystones 
4. See nothing in menu

### Expected behavior

I expect after revisiting all the waystones, that i can see them in the menu and teleport on them

### Mod Version

v3.0.4

### Minecraft Version

1.19.3 or newer

### Java Version

Java 18

### Fabric Version

- **Fabric:** ex. 0.14.9-1-19-2
- **Fabric API:** ex. 0.63.1+1.19.2

### Anything else?

I dont know if you can edit the report here, but i will try to add here some images later

**Comment by LordDeatHunter** [comment]
You're running version 3.0.4 of the mod, correct? If so, please update to the latest (3.0.5) and try again.

**Comment by LordDeatHunter** [comment]
Was the problem fixed with that, and can this issue be closed 😊?

**Comment by Rinerak** [comment]
I asked him and even tried it. It works! Thank you so much. You can close this issue now :)
