### ISSUE TITLE
[Bug]: Waystones can't be mined on 1.19.3

### ISSUE THREAD

**Issue by kkriehl** [LordDeatHunter/FabricWaystones#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Breaking waystones to drop in item form does not work in the latest version 3.0.6 for Minecraft 1.19.3.

I tried tried every type of pickaxe, lower value for `waystone_block_hardness`, setting `waystone_block_required_mining_level` to zero and checked if the [permission switch statement](https://github.com/LordDeatHunter/FabricWaystones/blob/master/src/main/java/wraith/fwaystones/block/WaystoneBlock.java#L122) is reached by switching  `global_mode_toggle_permission_levels` to NONE, which made the waystones unbreakable, as expected.
 
In all cases - except when `global_mode_toggle_permission_levels` was set to NONE - the waystone would take the same time to break as if the used tool did not satisfy the required mining level (~10 seconds), and wouldn't drop anything. I tried the same with the previous version 3.0.5 and MC 1.19.2 (same version for Fabric and dependencies) and breaking with the automatically created configuration worked as intended: breaking with a wooden pickaxe didn't drop and took ~10 seconds and breaking with an iron pickaxe only took ~3 seconds and the waystone did drop as item.

### To Reproduce

1. Create new Minecraft instance with Fabric mod loader and only required mods for waystones
2. Create new world in creative mode
3. Give yourself a waystone and an iron pickaxe
4. Switch to survival mode
5. Place waystone
6. Break placed waystone with the pickaxe

### Expected behavior

The waystone should break and drop as an item in just a few seconds when mined with a pickaxe with a mining level of at least 1.

### Mod Version

v3.0.5

### Minecraft Version

1.19.3 or newer

### Java Version

Java 18

### Fabric Version

- **Fabric:** 0.14.12
- **Fabric API:** 0.70.0+1.19.3
- **owo-lib:** 0.9.3+1.19.3

**Comment by LordDeatHunter** [comment]
🤦‍♂️ can't believe it took me this long to notice... should be good in the upcoming version.
