### ISSUE TITLE
[Bug]: Can't forget waystone after deleting the chunk that has that waystone

### ISSUE THREAD

**Issue by Sukijadh** [LordDeatHunter/FabricWaystones#167]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I was deleting my unused world chunks to reduce my world size but I don't realize that the chunk I deleted has a waystone in it. I can't teleport to that waystone and cannot forget that waystone.

### To Reproduce

1. Put a waystone in a selected chunk
2. Save that waystone and name it
3. Delete that chunk
4. and now the waystone is gone but still remain in the saved waystone list

### Expected behavior

It should be removed from the list after I clicked "Forget Waystone", but it doesn't removed because the chunk that has that waystone has been accidentally deleted

### Mod Version

v3.0.5

### Minecraft Version

1.19.2

### Java Version

Java 17

### Fabric Version

- **Fabric:** ex. 0.14.10
fabric-api-0.70.0+1.19.2

### Anything else?

Where's the waystones save file located

**Comment by LordDeatHunter** [comment]
Not much for me to do here. I recommend reading [the wiki page](https://github.com/LordDeatHunter/FabricWaystones/wiki/Manual_Editing) if you plan on doing any manual modifications.
