### ISSUE TITLE
[Bug]: Waystones ocassaionaly teleporting to the wrong location

### ISSUE THREAD

**Issue by MissPotato** [LordDeatHunter/FabricWaystones#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using Nvidia Shadowplay I captured this [Ivideo](https://drive.google.com/file/d/1FhB3-0u1cx-krcEeFpkxnM60xBNxKdIl/view?usp=sharing) of the bug happening. The "Blazes" destination is selected but instead teleports to the location below it.

When it happens it always seems to be the option below the one I click on. 

I think maybe the buttons are slightly overlapping each other, as in the video I am very close to the bottom of the button. After trying a few more times it does seem to be the case.

### To Reproduce

1. Hosted on a linux centos server
2. Running the pack Progress:create
3. Hover at the very bottom of a button
4. Click
5. Teleport to the location under the highlighted button
6. See video

### Expected behavior

To teleport to the location I click

### Mod Version

v3.0.5

### Minecraft Version

1.19.2

### Java Version

Java 18

### Fabric Version

- **Fabric:** ex. 0.14.12
- **Fabric API:** ex.  0.73.2

**Comment by LordDeatHunter** [comment]
Damn, that was a stupid bug. Amazed how you found it at all, given that the difference was a pixel or 2 👀

**Comment by MissPotato** [comment]
My ability to find the dumbest of bugs astounds many, lmao. I'm actually an official bug tester for the mod Rocket Man in RimWorld because I was finding so many edge cases.
