### ISSUE TITLE
[Feature]: Only owner can change gloabal

### ISSUE THREAD

**Issue by MissPotato** [LordDeatHunter/FabricWaystones#178]
### Description

I had a player who didn't quite understand what global meant make every village they came across a global waystone. This flooded everyone's waystone menu with randomly generated waystones. They thought they needed to be global in able to teleport to them.

### Describe the solution you would like

Two solutions: 1) make it so villager waystones can't be made global or 2) make it so only the owner can make the global. (With OP override.)

**Comment by LordDeatHunter** [comment]
There's already a config option for that. Check the [wiki](https://github.com/LordDeatHunter/FabricWaystones/wiki/Configuration)

**Comment by MissPotato** [comment]
Oh weird, my config in this pack doesn't have that. Mine only has `"can_players_toggle_global_mode": true` Guessing the pack dev is using an old config, sorry! Will regen and change it then, thank you!

**Comment by LordDeatHunter** [comment]
Hmm, what version of the mod do you have?

**Comment by MissPotato** [comment]
3.1.5, regenerating the config worked. It was probably just a really old config, as the pack is pretty old.
