### ISSUE TITLE
[Bug]: Versions 3.0.7 have incorrect minecraft version in fabric.mod.json

### ISSUE THREAD

**Issue by MissPotato** [LordDeatHunter/FabricWaystones#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I manually downloaded 3.0.7 and checked inside the jar to look at the fabric.mod.json to check if it was actually incompatible with 1.19.2. As some mods are some mods aren't, and I know curseforges UI is jank thanks to the Beta.  The "minecraft": version flag says it supports ~1.19. After putting it in the mod in minecraft crashed. However the curseforge page says it only supports 1.19.3 so it's really not that big of a deal, as automated tools wont download it.

The actual bug just means that if someone does install the mod anyways it wont throw the "outdated mod" crash and instead crashes with a no class found.

### To Reproduce

1) install updated mod in 1.19.2
2) Get wrong type of crash

### Expected behavior

Get the Fabric "Encountered an error" window instead of a  NoClassFound error

### Mod Version

v3.0.7 or newer

### Minecraft Version

1.19.2

### Java Version

Java 18

### Fabric Version

- **Fabric:** ex. 0.14.17-1.19.2
- **Fabric API:** 0.75.1+1.19.2

### Relevant log output

```shell
https://mclo.gs/T6rgyAB
```

### Anything else?

It is such a minor issue, I debated even posting this. Ultimately, I decided you might want to know for future versions of the mod.

**Comment by LordDeatHunter** [comment]
Did you download the correct version, `Fabric Waystones 3.0.7 - MC1.19.2` instead of `Fabric Waystones 3.0.7 - MC1.19.3`?
I had `~1.19` since it came out, since I can't be sure what future versions might break, but I'll keep that in mind for the future.

**Comment by MissPotato** [comment]
At the time I wrote this CurseForge hadn't approved the 1.19.2 version, thanks for the heads up!
