### ISSUE TITLE
[Feature]: a creative only waystone which can be placed but cant be broken in survival

### ISSUE THREAD

**Issue by flick0** [LordDeatHunter/FabricWaystones#187]
### Description

something like what naturally generated waystones do but being able to place them anywhere we want

### Describe the solution you would like

or even an item can be added that makes a waystone unbreakable

**Comment by Noaaan** [comment]
While an option in waystones to do this natively would be better, you can work around this by using Minecrafts Debug Stick to change the "generated" blockstate to "true". This would achieve the same.
