### ISSUE TITLE
[Bug]: Config tab changes window size, causing weird rendering problems

### ISSUE THREAD

**Issue by Nitjsefnie** [LordDeatHunter/FabricWaystones#192]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description

Some mods may have trouble handling changed window size, such as:
Inventory Tabs: https://github.com/Andrew6rant/InventoryTabs/issues/86

### To Reproduce

1. Install Fabric Waystones + Inventory Tabs
2. Create a new world in Creative
3. Place a Waystone, open it and go into the config tab
4. Observe

### Expected behavior

My suggestion would be to keep the window size static

### Mod Version

v3.0.7 or newer

### Minecraft Version

1.19.3 or newer

### Java Version

Java 17

### Fabric Version

- **Fabric:** 0.14.17 for 1.19.3
- **Fabric API:** 0.76.0+1.19.3

**Comment by allanonmage** [comment]
I came here to report this in 1.19.2, but it looks like someone beat me to the punch.

wraith-waystones-3.0.7+mc1.19.2.jar
inventorytabs-0.8.1-1.19.x.jar
fabric-server-mc.1.19.2-loader.0.14.19-launcher.0.11.2.jar


https://www.curseforge.com/minecraft/mc-mods/inventory-tabs
