### ISSUE TITLE
[Bug]: Multiple names for the mod

### ISSUE THREAD

**Issue by allanonmage** [LordDeatHunter/FabricWaystones#195]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description

The mod is clearly branded "Fabric Waystones", but the mod file is "Wraith Waystones", and the namespace in the game is "fwaystone".  That's very confusing.  Please pick one naming convention/brand and stick with it.

### To Reproduce

Look for the mod file or look for commands and stumble around trying to find the filename or namespace when you thought the mod was called "fabric waystones"

### Expected behavior

Consistent naming convention for mod, jar file, and in-game namespace.

### Mod Version

v3.0.7 or newer

### Minecraft Version

1.19.2

### Java Version

Java 17

### Fabric Version

fabric-server-mc.1.19.2-loader.0.14.19-launcher.0.11.2.jar
fabric-api-0.76.0+1.19.2.jar

**Comment by LordDeatHunter** [comment]
I use `fwaystones` (short for fabric waystones) in all the internal files from version 1.19 onwards. `Wraith` is what I use as a "branding" name for all my mods.
I'm not planning on changing the internal name unless there is a serious issue with the mod.
Is there a reason why this was marked as a bug?

**Comment by allanonmage** [comment]
Your handle is LordDeatHunter, so where does Wraith fit into all this?

You could make an argument that it's an anti-feature instead of a bug, but it's broken when compared to the way every software in the history of software has been made.  Alternatively, if that was explained somewhere, it would make more sense.  More as in "technically more than 0", but still not very much sense.  To be honest, I still don't understand what you're doing or why.

For example, if the "company" or team name is Wraith, then using that as your handle, or in screenshots, or in the description, or in the wiki, or as a "brought to you by Wraith" would make it much more obvious that they are all related.

The same places could also explain that the namespace is different than the title, the way people refer to it, and the filename.
