### ISSUE TITLE
[Feature Requests] Several ideas possibly worth implementing!

### ISSUE THREAD

**Issue by Abbanon** [LordDeatHunter/FabricWaystones#2]
After some careful thought, I've accumulated several ideas for Waystones that might be worth implementing.
They are as follows...

## 1: Functionality
Currently, Waystones already come with an Ender Pearl *built in.*
**But what if they don't, and you have to manually add one to activate the Waystone for interaction?**
Think of it like the End Portal. In order to interact with that, you need to add Eyes of Ender.
So imagine having to add an Eye of Ender to the Waystone to access the teleportation GUI!

You can add an Eye of Ender to a Waystone by looking at it while right-clicking with one if your hand.
Once you add the Eye of Ender, the Waystone will become activated and stay activated until it is broken.
To break a Waystone, you need a Diamond level or greater pickaxe. (It has Obsidian in it afterall!)
Once an activated Waystone is broken, it drops two items: The *Waystone itself,* and the *Eye of Ender.*

## 2: Crafting Recipe
I propose this as the Waystone's new crafting recipe:

![Screenshot_4](https://user-images.githubusercontent.com/37251822/95540062-02c78b00-09be-11eb-8fd6-e460e7c2d25c.png)

*"Why an Emerald?"* you may ask? Because Waystones naturally generate in villages, afterall!
My original idea was to use a Diamond since its colours are visible in the original texture.

***But!***

## 3: Texture

After some modifications, I've come up with a new texture:

![2020-10-08_23 11 38](https://user-images.githubusercontent.com/37251822/95540522-fa238480-09be-11eb-83a8-16760e01db30.png)

This texture makes *only the front* of the Waystone have a hieroglyph, and also changes some other very minor areas.
Here is the file:

![waystone](https://user-images.githubusercontent.com/37251822/95540645-4c64a580-09bf-11eb-91fd-44153591f0c2.png)
*Originally, the texture had "Pos1x Was Here" written at the bottom, but I had to erase that because parts of it were appearing in the debris when you were breaking the Waystone:*
![2020-10-08_21 29 54](https://user-images.githubusercontent.com/37251822/95540752-9a79a900-09bf-11eb-8869-bdf1aae5060c.png)

## 4: Features

Here's a list of various visual and technical features what would be pretty cool to have:
- Have the Eye of Ender turn to "stare" at player who approaches (like Enchanting Table books)
- Make the Eye of Ender have small purple particles absorbing into it (like Ender Chests)
- Make purple particles appear and dissipate around player when they teleport (like Endermen)
- Replace the inventory texture with block model instead (like regular blocks)

***So what do you think? Are these good ideas? Would they make for good implementations?***

**Comment by silentnyte** [comment]
Feature request, add waypoint integration with Xaero, Voxel, Antique Atlas, etc...

**Comment by LordDeatHunter** [comment]
This sure took a while to do, but most of these are added in the last commit. CurseForge release coming in the next hour.
