### ISSUE TITLE
[Bug]: Config is reset when Minecraft starts

### ISSUE THREAD

**Issue by quiqueck** [LordDeatHunter/FabricWaystones#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The config file is reset when Minecraft starts.

### To Reproduce

1. Change config
2. Start Minecraft
-> Config is reset

### Expected behavior

The config file should not get reset.

### Mod Version

v3.1.1 or newer

### Minecraft Version

1.20 or newer

### Java Version

Java 17

### Fabric Version

- **Fabric:** ex. 0.14.21
- **Fabric API:** ex. 0.83.0+1.20

### Relevant log output

```shell
None
```

### Anything else?

-

**Comment by LordDeatHunter** [comment]
This was an issue with Towns & Towers. It was fixed on their side in a newer version.
