### ISSUE TITLE
lots per village in superflat

### ISSUE THREAD

**Issue by superon** [LordDeatHunter/FabricWaystones#21]
https://imgur.com/NqXv8zc
this is a thing

**Comment by LordDeatHunter** [comment]
What is the world seed? It works fine on my end.

**Comment by superon** [comment]
just about any superflat does from what i've tried, have tried a load... some villages span with none, some spawn with a whole bunch...  for example the seed "seed" has 3 waystones at 10000 10 -10000
fabric-api-0.29.0+1.16
wraith-waystones-1.1.0

**Comment by LordDeatHunter** [comment]
This should be fixed in the latest commit.
Releasing on CurseForge later today or tomorrow.
