### ISSUE TITLE
[Bug]: Global waystones become discovered and dont hide

### ISSUE THREAD

**Issue by Linguardium** [LordDeatHunter/FabricWaystones#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you use a global waystone, it is added to the discovered waystones. The hiding global waystones is ignored if the you have ever used the waystone in question. 

This creates a situation where clicking a global waystone once prevents you from ever hiding that waystone from the list without hiding ALL waystones from the list

### To Reproduce

set waystone global
use waystone to make it "discovered"
uncheck show global waystones

### Expected behavior

Hiding globals should take priority over discovered status. If someone intentionally hides global waystones, they should be hidden.

### Mod Version

v3.0.8

### Minecraft Version

1.19.2

### Java Version

Java 17

### Fabric Version

N/A, logic issue not FAPI issue

### Anything else?

issue still present in master branch 

https://github.com/LordDeatHunter/FabricWaystones/blob/36bc65f425d328ba1b8c2b2abe0639e6e5f4099b/src/main/java/wraith/fwaystones/block/WaystoneBlock.java#L310

if this was inside the bracket above, it would skip this if it were a global waystone

**Comment by LordDeatHunter** [comment]
The line of code you pointed out, I need that there in case the player ""discovers"" a global Waystone, which in the future gets toggled as non-global.
Maybe I can make a config option in the future...
