### ISSUE TITLE
[Bug]: Local Void issues

### ISSUE THREAD

**Issue by grundyboy34** [LordDeatHunter/FabricWaystones#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I've noticed some issues with the local void.
1) When local void teleports are set to free, you can only teleport if you have enough experience as if the teleport wasn't free. Otherwise it says you don't have enough experience.
2) If the local void teleports are set to not free, you simply can't teleport, attempting to use the local void does nothing.

### To Reproduce

1) Set local void teleports to free.
2) Set a distance based cost on waystones.
3) Notice that not having enough xp for teleport won't let you use local void.
4) Once you have enough xp, you can teleport and no experience is lost.
5) Set local void teleports to not free
6) Notice local void interaction does nothing, always unable to teleport with no error message.

### Expected behavior

Local void

### Mod Version

v3.1.1 or newer

### Minecraft Version

1.20 or newer

### Java Version

Java 18+

**Comment by LordDeatHunter** [comment]
Yikes, surprised no one reported this sooner...
