### ISSUE TITLE
NullPointerException when joining single-player world 

### ISSUE THREAD

**Issue by cryxli** [LordDeatHunter/FabricWaystones#22]
Hi! I really like your take on waypoints. Unfortunately something is wrong with the last two versions...

### Observation 
With (latest) version 1.1.0 I cannot join a world created with 1.0.10 (may have been one before that, cannot remember).

See [latest.log](https://github.com/LordDeatHunter/FabricWaystones/files/5761037/waypoint.log)

I can join the world, when I revert to version 1.0.10. (However, when jumping world, I sometimes get the same NullPointerException. That is teleporting from the Overworld into the Nether. Or Overworld into the End. Even chunk-loader does not always help e.g. jumping back from the End to the Overworld to a Waypoint in my chunk-loaded base.)

### Setup

- Minecraft 1.16.4
- Fabric Loader 0.10.8
- Fabric API 0.29.1+1.16
- Wrath Waystones 1.1.0

If it helps, I can try to reduce the number of mods... Problem is, I do not know what causes the error and therefore how to reproduce it in a simpler setup.

### Speculation

I only looked briefly over your code. I would guess that your client code expects some constants to be initialised, but the init is done in a server side only code block. Check where WaystonesClient.WAYSTONE_DATABASE is initialised. I can be very much completely wrong!

Cheers,
cryxli

**Comment by LordDeatHunter** [comment]
Fixed 👍
