### ISSUE TITLE
[Bug]: people can leave and rejoin the server to bypass timelimits on items and teleporting. Timelimit blocks the use of any teleportation when only one item has a time penalty

### ISSUE THREAD

**Issue by Sipxer** [LordDeatHunter/FabricWaystones#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

n/a

### To Reproduce

1. make pocket wormhole have a timelimit and only the pocket wormhole
2.  teleport to a waystone using the pocket wormhole
3. leave game
4. rejoin game
5. see that the timelimit has been reset

### Expected behavior

the timelimit should stay in effect between getting off and logging back on

### Mod Version

v3.1.1 or newer

### Minecraft Version

1.20 or newer

### Java Version

Java 18+

### Fabric Version

- **Fabric:** ex. 0.12.5-1-17-1
- **Fabric API:** ex. 0.42.1+1.17

**Comment by LordDeatHunter** [comment]
Oops, nice catch! Fixed for 1.20.2
