### ISSUE TITLE
[Bug]: Wiki: missing info if it is server-only

### ISSUE THREAD

**Issue by McLaynV** [LordDeatHunter/FabricWaystones#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was unable to find the information if this mod is server-only, or if it has to be installed on clients as well. Could you please add it to the Wiki?

### To Reproduce

I would expect it on the [main page](https://github.com/LordDeatHunter/FabricWaystones/wiki) of the Wiki

### Expected behavior

I would expect it on the [main page](https://github.com/LordDeatHunter/FabricWaystones/wiki) of the Wiki

### Mod Version

v3.1.1 or newer

### Minecraft Version

1.20 or newer

### Java Version

Java 17

**Comment by LordDeatHunter** [comment]
It is marked as such on both CurseForge & Modrinth, and I think it's pretty obvious that a mod that adds new blocks & items is required on both sides, no?

**Comment by McLaynV** [comment]
Thank you for the answer. I confirm that it is marked as server+client on [Modrinth](https://modrinth.com/mod/fwaystones). 
However, this information is either well-hidden or missing on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones) and in the [GitHub Wiki](https://github.com/LordDeatHunter/FabricWaystones/wiki).

A few years ago, I would agree that it is obvious that adding new items and blocks means the mod has to be both server-side and client-side. However, I returned to using mods in MineCraft after a few years and the first mod I tried ([Get Off My Lawn ReServed](https://github.com/Patbox/get-off-my-lawn-reserved)) adds new items, blocks, crafting recipes, even GUI... and it is server-only.

**Comment by LordDeatHunter** [comment]
Yes, CurseForge is a big pain when it comes to versioning & such.
GOML (and similar mods) use some tricks to "fake" item/block additions & such, but as you've said, those "tricks" are becoming less and less obvious with each new version.

I added 2 new pages to the wiki, give it a check :)
