### ISSUE TITLE
[Bug]: Activated Waystones vanish off the list.

### ISSUE THREAD

**Issue by Ylgnik** [LordDeatHunter/FabricWaystones#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was adventuring in Medieval Minecraft 2 (I was told to report the bug here) and for some reason after getting quite a bit of waystones activated from different villages, the ones I had on my list vanished and only 2 of them were left. 

I went back to my home ( which didn't have its waystone listed anymore ) and when I clicked on the waystone, it said that "Home was Discovered" even though I've had it discovered already.

### To Reproduce

There aren't really any steps to show, as it was random.

### Expected behavior

The waystone list shouldn't just vanish.

### Mod Version

v3.1.1 or newer

### Minecraft Version

1.20 or newer

### Java Version

Java 18+

### Fabric Version

Fabric API - 0.89.0+ 1.20.1
Fabric - 0.14.22

**Comment by LordDeatHunter** [comment]
I think this should be fixed in the latest version. The fix is out for 1.20.2, I will be releasing a backport to 1.20.1 shortly. Feel free to reopen if it persists.
