### ISSUE TITLE
[Bug]: waystones accross dimension at the same coords overwrite each other

### ISSUE THREAD

**Issue by Minionflo** [LordDeatHunter/FabricWaystones#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you place a Waystone at 0 100 0 in the Overworld and the same in the Nether only one is shown in the menu.

### To Reproduce

1. place a waystone at 0 100 0 in the overworld
2. place a waystone at 0 100 0 in the nether
3. try to warp between them

### Expected behavior

that they dont overwrite each other

### Mod Version

v3.1.1 or newer

### Minecraft Version

1.20 or newer

### Java Version

Java 18+

### Fabric Version

- **Fabric:** ex. 0.14.22-1.20.1
- **Fabric API:** 0.89.3+1.20.1

**Comment by LordDeatHunter** [comment]
Wow...that's so stupid from my side 🤦‍♂️
This might fix a lot more issues than just this... thanks for noticing this, I've been trying to replicate this since forever...
