### ISSUE TITLE
[Feature]: Make latest version compatible with 1.20.1

### ISSUE THREAD

**Issue by theavandiepen** [LordDeatHunter/FabricWaystones#230]
### Description

Minecraft 1.20.1 crashes when I try to load my world with the latest Waystones version installed. If I try to also have the latest owo lib installed, Minecraft crashes at launch.

### Describe the solution you would like

I would very much like to have the fix to the zombie village issue with Repurposed Structures be playable on my 1.20.1 world. 

I can't update to 1.20.2 yet because Quilt's version of Fabric API isn't yet compatible with 1.20.2 and a number of the mods I'm using rely on it (and won't work with the regular Fabric API).

**Comment by LordDeatHunter** [comment]
Done, file should be up in a couple of minutes.

**Comment by theavandiepen** [comment]
Thank you so much!
