### ISSUE TITLE
[Bug]: Waystones keeps disapearing in List

### ISSUE THREAD

**Issue by Hastemir** [LordDeatHunter/FabricWaystones#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I updated my World from Server to local, from 19.2 to 20.2
and ofc this mod.

But the Waystone list keeps vanishing.
Even ingame. 
I port my self to the locations and reactive them and after like 8-10 waystones
7-9 disapear from list.

### To Reproduce
Testet it even on a new fresh world. Still Happening.
.

### Expected behavior

.

### Mod Version

v3.1.1 or newer

### Minecraft Version

1.20 or newer

### Java Version

Java 18+

### Fabric Version

- **Fabric:** 0.14.24
- **Fabric API:** 0.90.4

### Anything else?

My Mods:
architectury-10.0.8-fabric
balm-fabric-1.20.2-8.0.1
cloth-config-12.0.109-fabric
collective-1.20.2-6.72
deepslatecutting-fabric-1.7.0
fabric-api-0.90.4+1.20.2
fabric-language-kotlin-1.10.10+kotlin.1.9.10
FallingTree-1.20.2-5.0.3
ForgeConfigAPIPort-v9.0.0-1.20.2-Fabric
freecam-fabric-1.2.1.1+1.20
iris-mc1.20.2-1.6.10
lambdynamiclights-2.3.2+1.20.1
litematica-fabric-1.20.2-0.16.0
malilib-fabric-1.20.2-0.17.0
modmenu-8.0.0
netherportalfix-fabric-1.20.2-14.0.0
owo-lib-0.11.3+1.20.2
passiveshield-1.20.2-3.2
reeses_sodium_options-1.7.0+mc1.20.2-build.97
satin-1.14.0
shulkerboxtooltip-fabric-4.0.7+1.20.2
SimpleDiscordRichPresence-fabric-4.0.2-build.36+mc1.20.1
sodium-extra-0.5.3+mc1.20.2-build.114
sodium-fabric-mc1.20.2-0.5.3
soulfired-1.20.2-3.2.0.1-fabric
stackrefill-1.20.2-4.0
starlight-1.1.3+fabric.5867eae
wraith-waystones-3.2.0+mc1.20.2
yet-another-config-lib-fabric-3.2.1+1.20.2
Zoomify-2.12.0

**Comment by LordDeatHunter** [comment]
Unfortunately, this issue was expected and written in the changelog, and there's not much that can be done, other than resetting the Waystone data, or creating a new world.
![image](https://github.com/LordDeatHunter/FabricWaystones/assets/26803198/cd19bab8-8b90-43f0-8e53-82e6711933b1)

**Comment by Hastemir** [comment]
I said it happens also on New Worlds !
but only in Single Player.

if i run a Server this bug doesnt appear.

**Comment by LordDeatHunter** [comment]
Can you try the latest version? I made some new fixes which should hopefully resolve that problem.
If it still exists, please reopen this issue.
