### ISSUE TITLE
[Feature]: Config to make waystones not craftable.

### ISSUE THREAD

**Issue by Allexio** [LordDeatHunter/FabricWaystones#235]
### Description

Hi there,

In my modpack, I have multiple traversal options that are added in such as Create with its trains.
In an effort to encourage players to use those instead of just waystoning everywhere, I would like to make it so waystones cannot be crafted and are only placed in villages when generated.

### Describe the solution you would like

A simple "Is craftable" boolean config option that changes the item recipe to require something that isn't normally obtainable in game.

### Anything else?

Thank you for taking the time to consider this :smile:

**Comment by LordDeatHunter** [comment]
Check [the wiki](https://github.com/LordDeatHunter/FabricWaystones/wiki/FAQ#how-do-i-removechange-a-recipe).
