### ISSUE TITLE
[Bug]: Server keep crashing

### ISSUE THREAD

**Issue by MK-404** [LordDeatHunter/FabricWaystones#237]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description

[crash-2023-11-15_11.17.24-server.txt](https://github.com/LordDeatHunter/FabricWaystones/files/13363292/crash-2023-11-15_11.17.24-server.txt)

### To Reproduce

i just start the server lol

### Expected behavior

idk i think just start the server

### Mod Version

v3.1.1 or newer

### Minecraft Version

1.20 or newer

### Java Version

Java 18+

### Fabric Version

- **Fabric:** 0.14.23 - 1.20.1
- **Fabric API:** 0.90.7 - 1.20.1

**Comment by JRPGames** [comment]
I have this issue as well.

[crash-2023-12-21_07.37.18-server.txt](https://github.com/LordDeatHunter/FabricWaystones/files/13737568/crash-2023-12-21_07.37.18-server.txt)
[crash-2023-12-21_07.40.20-server.txt](https://github.com/LordDeatHunter/FabricWaystones/files/13737570/crash-2023-12-21_07.40.20-server.txt)
[crash-2023-12-21_07.33.42-server.txt](https://github.com/LordDeatHunter/FabricWaystones/files/13737571/crash-2023-12-21_07.33.42-server.txt)

**Comment by LordDeatHunter** [comment]
This is already fixed. Update to 3.3.2
