### ISSUE TITLE
[Bug]: waystones repeated and cannot be forgotten

### ISSUE THREAD

**Issue by Yhon127** [LordDeatHunter/FabricWaystones#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The waystones appear repeated in the selection menu. They work but the repeat cannot be eliminated even by destroying the waystone. Afterwards the bug no longer occurred and the waystones discovered after this are no longer repeated.
![image](https://github.com/LordDeatHunter/FabricWaystones/assets/124219620/905259e1-39f7-4679-acfc-fae5342e0970)
![image](https://github.com/LordDeatHunter/FabricWaystones/assets/124219620/f8805138-9eae-4b32-9415-c40a9cedc483)
![image](https://github.com/LordDeatHunter/FabricWaystones/assets/124219620/5a3da4fe-995b-4a33-b24b-bb630028d81a)

### To Reproduce

I don't know how to reproduce this thing, some waystones are working as intended but others out of nowhere they were rediscovered.

### Expected behavior

that they do not repeated in the menu and you can forget the waystones

### Mod Version

v3.1.1 or newer

### Minecraft Version

1.20 or newer

### Java Version

Java 18+

### Fabric Version

- **Fabric:** ex. 0.12.5-1-17-1
- **Fabric API:** ex. 0.42.1+1.17

**Comment by Yhon127** [comment]
I figured out how to fix this, delete the f waystones data form the world in the saves folder but you will need to click again in every waystone in order to show them in the menu.

**Comment by LordDeatHunter** [comment]
Oh wow, I never got around to backporting the fix for this to older versions...
