### ISSUE TITLE
[Feature]: Towers of the Wild Modded Compat

### ISSUE THREAD

**Issue by Driestcombee** [LordDeatHunter/FabricWaystones#254]
### Description

It feels a bit more natural for Fabric Waystones to spawn in towers, similarly to how regular waystones can spawn in TOTW towers.

### Describe the solution you would like

Waystones from the Fabric Waystones mod would spawn on the tops of TOTW towers.

### Anything else?

![tower taiga](https://github.com/LordDeatHunter/FabricWaystones/assets/142123085/321c8da6-119d-4b70-8438-83e34a04cf7c)
![tower jungle](https://github.com/LordDeatHunter/FabricWaystones/assets/142123085/e68a4ef9-d805-4129-8dd3-f932f43dbc25)
![tower desert](https://github.com/LordDeatHunter/FabricWaystones/assets/142123085/d41b3800-3cc4-4a8f-a80c-b014726e5177)

A few examples

**Comment by LordDeatHunter** [comment]
This should already be implemented, tho? Unless it was removed in some version of TOTW 🤔

**Comment by Driestcombee** [comment]
odd

**Comment by Driestcombee** [comment]
well it might need to be reimplemented on the latest version

**Comment by Sam-Chai** [comment]
Well, I fork a totw for this waystone mod for my server use.
Here is the repo (btw, totw is fully-datapack-drive, so just optimize NBT data)
[https://github.com/Sam-Chai/TowersOfTheWildModded](https://github.com/Sam-Chai/TowersOfTheWildModded)
I think it can help you.
