### ISSUE TITLE
Waystone knowledge should be saved by player's UUID not by player's name

### ISSUE THREAD

**Issue by Cynosphere** [LordDeatHunter/FabricWaystones#29]
I use [Drogtor the Nickinator](https://www.curseforge.com/minecraft/mc-mods/drogtor) on a server that has Waystones on it, and another player and I realized that our known waystones were wiped after we set a nickname. Also because of Drogtor having no name enforcement, what stops a player from accessing or even modifying another player's waystone list.

**Comment by LordDeatHunter** [comment]
Oh, that's a good idea. The waystone system is getting a rewrite soon either way.
