### ISSUE TITLE
[Feature Request] Enable color codes in lang files

### ISSUE THREAD

**Issue by ruvaldak** [LordDeatHunter/FabricWaystones#35]
Currently, the color of various words/names throughout the mod are preset (Grey title, black XP cost, etc). Enabling the ability to set the color of these in the lang files with color codes (§f for white, for example) would allow greater customizability for resource packs attempting to modify the UI - specifically ones aiming for a "dark mode" of sorts.

**Comment by LordDeatHunter** [comment]
I changed a bunch of them in the latest version. There are still some left to do tho.
Not marking as closed for the time being.

**Comment by LordDeatHunter** [comment]
I had some really cursed stuff before. Should be good now. Go wild :)
