### ISSUE TITLE
NA AOF3 2.8.1 Server Crash

### ISSUE THREAD

**Issue by irunatbullets** [LordDeatHunter/FabricWaystones#37]
A player broke a waystone which crashed the official NA AOF3 server.

(mapped) https://paste.alloffabric.com/situkotezi.yaml

When the server rebooted the player said that half of the waystone is still there, but they're going to leave it alone.

This pops up from time to time, but I keep forgetting to submit and issue.

**Comment by irunatbullets** [comment]
Tracking against https://github.com/TeamAOF/All-of-Fabric-3/issues/396

**Comment by Pyrogeen** [comment]
I'm the player that crashed it.
To specify, due to (probably) generation collisions only the top half of the waystone was there, breaking it resulted in a crash.

**Comment by LordDeatHunter** [comment]
I am working on a re-work of the entire mod. This (and many other bugs) will be fixed in the near future. Please be patient :) Rewriting a mod takes a bit.

**Comment by Seikm** [comment]
@LordDeatHunter Do you have any predictions for when you will release this rework? I also have a lot of bugs, when I rename some waystone on my server, my game crashes.

**Comment by LordDeatHunter** [comment]
I got a big part of it done. If everything goes well then hopefully in a day or 2.
If you want, you can add me on discord DH#9367 and I will send you beta builds for testing.

**Comment by LordDeatHunter** [comment]
Hopefully this fixes everything. Uploading on CurseForge in a bit.
