### ISSUE TITLE
[Feature Request] Config options to make escaping danger harder

### ISSUE THREAD

**Issue by JumperCzech** [LordDeatHunter/FabricWaystones#39]
Right now its ridiculously easy to use a Local Void or Abyss Watcher (which aren't particularly expensive) to escape any remotely dangerous situation. Falling into void, lava, or even mobs of enemies.
The easiest solution would be having a timer of configurable lenght start when you attempt teleportation and have the teleportation only happen after it passes.
It would also be nice if there was an option to make the timer reset or cancel if the person gets hit or moves.

**Comment by LordDeatHunter** [comment]
Bit late, but done.
