### ISSUE TITLE
Chunks Not Loading on Teleport

### ISSUE THREAD

**Issue by TheCoolestPaul** [LordDeatHunter/FabricWaystones#4]
When I go through a way stone I usually have to disconnect from the server and join back in order to get the world to load.

**Comment by budgej** [comment]
Try reloading chunks with F3 + A?

**Comment by LordDeatHunter** [comment]
I have never been able to replicate this issue. I am closing this for the time being, seeing as it most likely was some lag related issue. If it still occurs, re-open the issue and I'll make a quick fix by reloading the world on teleport.
