### ISSUE TITLE
Nonglobal waystones disappearing.

### ISSUE THREAD

**Issue by lolman9998** [LordDeatHunter/FabricWaystones#44]
[latest.log](https://github.com/LordDeatHunter/FabricWaystones/files/6797443/latest.log)
(Log, but it might not help much, as this was found during a long session)

When I access a new unclaimed waystone my nonglobal waystones do not show up. Global ones always show up.

**Comment by LordDeatHunter** [comment]
Do you perhaps have non-globals hidden in the waystone settings menu?

**Comment by lolman9998** [comment]
There does not seem to be an option to hide/unhide globals, so it is following default behavior

**Comment by lolman9998** [comment]
Well, the problem was the game was lagging so the scroll region didnt actually scroll. After a couple restarts it decided to work. Sorry to waste your time. (Although maybe an option for a bigger interface would be nice so you can see more waystones, also maybe something to mark which waystones are global.) Dunno if you wanna close the issue, so I won't.
