### ISSUE TITLE
Can't place waystones above 256 blocks (when increasing the world height)

### ISSUE THREAD

**Issue by Mnky313** [LordDeatHunter/FabricWaystones#49]
There is a mod in our modpack (caves and cliffs part 2) that increases the world height to the 1.18 values (-64 - 320).

The waystone will not let you place it above the normal 256 block limit. (Nothing happens when placing the block)

**Comment by LordDeatHunter** [comment]
Coincidentally, I fixed this while doing something completely different.
Wait for v2.2.0+ on CF
