### ISSUE TITLE
[Feature Request] Waypoint Integration with mapping mods

### ISSUE THREAD

**Issue by silentnyte** [LordDeatHunter/FabricWaystones#5]
Add waypoint integration with Xaero, Voxel, Antique Atlas, etc...

**Comment by mysticdrew** [comment]
@LordDeatHunter I have recently released Journeymap for fabric. We have a pretty easy to use API if you wish to integrate and add waypoint support. Feel free to reach out if you need assistance. 
https://github.com/TeamJM/journeymap-api/blob/1.18.2_1.8-fabric/docs/howto.md
