### ISSUE TITLE
[Mod Compatability Issue] Bountiful

### ISSUE THREAD

**Issue by Coffe-e** [LordDeatHunter/FabricWaystones#62]
I've noticed that with the Fabric Bountiful mod, Bounty-Boards can generate over Village Waystones. While this could be an issue on their end, they had no github to report issues to.

It is also (somewhat) fixed by reducing the spawnrate of Bounty Boards, but it doesn't fix the issue.

**Comment by LordDeatHunter** [comment]
Is this in all villages or only in some villages?
If it's in some villages only, can I have a seed with such a village?

**Comment by Coffe-e** [comment]
It depends on what you put in the bountiful config for "boardGenerationFrequency". It happened consistently at it's default value (4), but when I changed it to 2, it seemed to fix it. However, there were occasionally some villages that had no waystone. I'll get you the seed ASAP as well.

**Comment by Coffe-e** [comment]
What I noticed is that both bounty boards and waystone pedestals seem to generate in the same spots relative to a village's buildings and roads, though i'm not actually sure how modded structures are added to vanilla villages, this is just speculation on my part.

Seed: -9159457211973149654, closest village using /locate village command

**Comment by LordDeatHunter** [comment]
I think I got a fix. Can you either add me on discord: DH#9367
or join my dev server:
https://discord.gg/vMjzgS4
for testing, before I make a release?

**Comment by Coffe-e** [comment]
Dunno if this will reopen the issue or not (hopefully not), but I just wanted to apologize for not being able to help test this. It was super late where I live so I had to go to sleep. Glad to see that it looks like you've fixed the issue though.

**Comment by Coffe-e** [comment]
If you didn't get a chance to fix it though, I can still help test it out. I joined the server you linked, and my name on discord is "TEA", if you need to contact me for it.
