### ISSUE TITLE
Dupe waystones

### ISSUE THREAD

**Issue by OnionAce** [LordDeatHunter/FabricWaystones#67]
If you place down a waystone and brake it with a hammer that mines 3x by 3x it dupes the waystone.

**Comment by Encrypted-Thoughts** [comment]
Currently playing on a 1.18.2 server with both hammers and this mod so looked into it a bit.

Noticed that duping doesn't happen with end brick waystones which led me to notice that there's no loot table asset for end brick waystones unlike the others. So I removed the loot table assets and it seems to fix the duping with hammers.

Is it ok to remove those loot table assets or will that cause some other problem? If so should the end brick waystone have an associated loot table like the others?

**Comment by LordDeatHunter** [comment]
Hmm, that's interesting. You can probably remove the loot tables with no issues.

**Comment by Encrypted-Thoughts** [comment]
Cool, that's what I thought since it seems to be handling the block break in WaystoneBlock. 

For some reason it only seems to trigger the WaystoneBlock break once when you break both sections at once with a hammer then guessing it falls back on the loot table for the other section of the block.

**Comment by LordDeatHunter** [comment]
I never wanted to hardcode the drop logic in the actual code, but I was having issues with the vanilla loot tables...
I'll remove them for now, hopefully I'll find something better in the future.
