### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by EnderBro123** [LordDeatHunter/FabricWaystones#7]
Mods are in the file.

[crash-2020-10-28_21.29.27-client.txt](https://github.com/LordDeatHunter/FabricWaystones/files/5456153/crash-2020-10-28_21.29.27-client.txt)

**Comment by gdude2002** [comment]
I can also confirm this crash. It appears that Waystones is built against an old version of Fabric API.

[message.txt](https://github.com/LordDeatHunter/FabricWaystones/files/5467066/message.txt)
