### ISSUE TITLE
Abyss watcher no longer shows on top of waystones on 2.2.0

### ISSUE THREAD

**Issue by Justsnoopy30** [LordDeatHunter/FabricWaystones#70]
![2021-11-12_17 12 34](https://user-images.githubusercontent.com/33374736/141594004-0a94b3e7-b65a-4ed4-a43f-7743505d5719.png)

**Comment by LordDeatHunter** [comment]
They only show on top of active (claimed) waystones.
If this waystone has been claimed before the update and there is no abyss watcher, for the time being, unclaim then claim again.

**Comment by Justsnoopy30** [comment]
Yes I've claimed it before. Have exactly do I unclaim it so I can claim it again?

**Comment by LordDeatHunter** [comment]
In the waystones config gui there's a trash can icon for revoking ownership. Closing then opening the wayatone again will re-claim it.
As of 2.2.1, I made it so that it refreshes the Active state on right click even without unclaiming it.
