### ISSUE TITLE
Villages can turn out a little bit smaller due to structure removal

### ISSUE THREAD

**Issue by Fourmisain** [LordDeatHunter/FabricWaystones#74]
While debugging the issue of https://github.com/LordDeatHunter/FabricWaystones/pull/73 I found another small one.

There's this code here which ensures waystones are unique in each village:
https://github.com/LordDeatHunter/FabricWaystones/blob/e11e7d0d116d1285f971f25f34ee4caa17580c2f/src/main/java/wraith/waystones/util/Utils.java#L251-L271

It does this by removing all structures that contain waystones except 1.

This means if a village were to generate with multiple waystones, because those structures are getting removed without replacement, the village will actually be smaller than intended.

To demonstrate this I boosted the weighting of waystone structures from 5 to 500 here:
https://github.com/LordDeatHunter/FabricWaystones/blob/f3f8b63903c3671f34347c55ee970fdf2801bcd7/src/main/java/wraith/waystones/util/WaystonesWorldgen.java#L36

Here's a village without waystone generation:
![without](https://user-images.githubusercontent.com/8464472/142060073-6275656d-3e7d-4427-8ac8-eab438d98472.png)
Here's the same village with the boosted waystone generation:
![with500](https://user-images.githubusercontent.com/8464472/142060024-eb80c25c-c96e-478e-a224-6d0a5f9e713b.png)

Of course this comparison is heavily exaggerated, but it's still an issue to a lesser degree.

**Comment by LordDeatHunter** [comment]
Finally fixed.
