### ISSUE TITLE
Compatibility issue with Repurposed Structures

### ISSUE THREAD

**Issue by Xastabus** [LordDeatHunter/FabricWaystones#77]
Minecraft 1.18-rc3 & rc4
Repurposed Structures 3.1.1+1.18-rc3
wraith-waystones-2.3.0

Problem: Waystones do not generate in Mushroom Village (possibly other villages not normally found in Vanilla Minecraft).  Repurposed Structures attempt to generate a Waystone in a Mushroom Village stalls the server.

Waystones do generate in "Vanilla" villages generated by Repurposed Structures.

Example of the problem: Mushroom island NE of spawn, Seed: [-1166828785]

https://pastebin.com/TnSpNA7a

**Comment by Xastabus** [comment]
References: https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/159

**Comment by LordDeatHunter** [comment]
2.3.0 is a beta release. I have something that should fix everything RS-related in the next update.

**Comment by Xastabus** [comment]
I saw your 2.3.1 update posted to CurseForge.  This fixed the problem, thanks!

**Comment by Xastabus** [comment]
RS Compatibility problem is back in Waystones 2.3.2

-------------------------------------------------------------------
Repurposed Structures: Failed to create valid structure with all required pieces starting from this pool file: repurposed_structures:villages/birch/town_centers. Required pieces failed to generate the required amount are: [waystones:village_waystone=1]
  Make sure this structure's size in the config (if it has one) is not set too low.
  Also make sure the max height and min height for this structure in the config (if it has one) is not too close together.
  If min and max height is super close together, the structure's pieces may not be able to fit in the narrow range and spawn.
  Otherwise, if the min and max height ranges aren't close, and structure size isn't super small like 1 or 2, and this message still appears,
  please report the issue to Repurposed Structures's dev with latest.log file!

**Comment by Xastabus** [comment]
I switched my modpack back to Waystones 2.3.1 and got the same error... I'm retesting a previous modpack instance.

**Comment by Xastabus** [comment]
The issue seems to be caused by datapacks I added to the world.  I'll just remove the datapacks.
