### ISSUE TITLE
Feature Request: Allow Removal of Waystones from a players list

### ISSUE THREAD

**Issue by fretboardfreak** [LordDeatHunter/FabricWaystones#8]
Hi LordDeatHunter,

I've been enjoying the mod so far. It's very nice to have this functionality for Fabric.

I have found however, that if I activate a Waystone and then later break the block it will still appear in the list of targets and will allow me to teleport to the location the Waystone used to be.  It does not appear that there is a way for a player to remove unwanted or non-existent waystones from their list at this time.

I see a couple of possible ways to allow something like this:
- could provide a button or key combo in the UI to let the player manually clean up entries they do not want in the waystone list.  This might by handy in case a person wants to remove a Waystone from their own list without breaking the actual block.
- could try to remove a waystone from all player lists when the block is broken.  This might present challenges for example with players on servers that are logged off.  I don't know.
- some other fancy solution I hadn't thought of :)

I'm not very familiar with the available APIs otherwise I would offer to help out a bit more.
Thanks for all your efforts. Take care.

fretboardfreak

**Comment by LordDeatHunter** [comment]
It should already "undiscover" the waystone on breaking. Do you have any
other mods? What gamemode? Are you breaking the block yourself or with
something like tnt?

**Comment by fretboardfreak** [comment]
I'm in survival, fabric 1.16.3.  I do have fair set of mods in place and have not yet ruled out interaction with another mod. 

I just did a quick test with only the fabric-api and your Waystones mod and it is working as you describe.
I may try to do some further testing today to see if I can find the mod that was causing the waystones to not be cleaned up.

That said, it would still be a nice feature for the player to be able to choose to remove a waystone from their list even if the waystone remains present in the world.  For example, on a server with a handful of players there may be a set of public waystones that everybody uses and then the players might have other waystones that they set up for themselves.  

It might be nice to be able to curate the list of waystones presented to the player.  For example, it would be nice to be able to sort my Home waystone to the top of the list and I might want to remove a waystone that I use infrequently so that I do not have to scroll past it in the list to find the target that I want.  I am perfectly happy having to "rediscover" the waystone in order to add it back to my list.

So I guess this is a feature request to allow the user to sort and/or remove the Waystones presented to them in the UI.

**Comment by LordDeatHunter** [comment]
Done :)
(I pushed the changes to github, but I still haven't posted on CurseForge)
