### ISSUE TITLE
[Bug] Falling off the world after using waystone while sitting on a horse

### ISSUE THREAD

**Issue by Ninja-Recai** [LordDeatHunter/FabricWaystones#93]
Hi! 😊 
I noticed two problems with using waystones while sitting on a horse:
1. The horse does not teleport with me.
2. For some waystones I fall off the world after using it while sitting on a horse.

Mod version: 2.4.1
Game version: 1.18.1

I'm playing on a multiplayer server.

**Comment by LordDeatHunter** [comment]
Are you (as well as the server) using Fabric API version 0.42.1 or newer? Older versions might be causing some issues.

**Comment by Ninja-Recai** [comment]
We are using fabric api 0.45.2

**Comment by LordDeatHunter** [comment]
I'll look into it. It would be useful if you could lend me the "latest.log" file, just in case.

**Comment by Ninja-Recai** [comment]
Sure! Please see the log file attached.

[latest.log](https://github.com/LordDeatHunter/FabricWaystones/files/7874044/latest.log)

**Comment by wolvyreen** [comment]
any news on this? I teleports on my horse for the first time today and was ported to the destination waystone fine except I was at -57 and had to convert my game to creative temporarily just to get back to the surface.

**Comment by LordDeatHunter** [comment]
Closing this one in favor of #168, since it covers other mobs (as well as non-mounts).
