### ISSUE TITLE
Experience Consuming Can't Display Correctly in version fabric-2.4.1

### ISSUE THREAD

**Issue by SpaceTeleport** [LordDeatHunter/FabricWaystones#94]
As we all know, in Survival Mode, every teleport consumes 1 level.
But there is a bug that when you succeed to a teleport, the experience bar on the Client screen DOESN'T CHANGE, though actually it changes on Server and doesn't correctly display on Client until another update on the experience bar occurs, like absorbing an experience ball.
So I guess that you need an update on the experience bar after your teleport code being executed.

**Comment by SpaceTeleport** [comment]
By the way, the minecraft version is 1.18.1.

**Comment by SpaceTeleport** [comment]
how to add this issue a tag?

**Comment by SpaceTeleport** [comment]
Mincraft Version: 1.18.1
Fabric api version: 0.46.1
Mod version: 2.4.1

**Comment by SpaceTeleport** [comment]
I have seen the latest.log, but the Client doesn't print anything so I can't find the exact reason.

**Comment by LordDeatHunter** [comment]
This is a vanilla Minecraft issue.
https://bugs.mojang.com/browse/MC-124177
I had a fix for it in the older versions when I was using my own teleport system.
I recently changed to using the Fabric API's teleport system, which fixes a lot of other desync issues.
I will not be fixing this on my end, and instead I'll either open an issue or PR in the Fabric API.

**Comment by LordDeatHunter** [comment]
My bad, the original issue is for between different dimensions. Fabric dimensions API does fix that.
This issue is not related to that. I've fixed it and will be releasing an update on CF shortly.
