### ISSUE TITLE
[Bug] Vehicles don't teleport with player, causing desync.

### ISSUE THREAD

**Issue by LordDeatHunter** [LordDeatHunter/FabricWaystones#95]

**Comment by wolvyreen** [comment]
Also can confirm this!  sitting on a horse caused me to teleport to -57 of the destination waystone.  Had to convert gamemode to creative and teleport myself back to the surface because I couldnt even mine myself out.

**Comment by LordDeatHunter** [comment]
Closing as duplicate of #93
