### ISSUE TITLE
how to use in the nether and the end

### ISSUE THREAD

**Issue by lznEureka** [LordDeatHunter/FabricWaystones#96]
I noticed that in creation mode, I can freely tp in the nether to nether, nether to the overworld, how do I configure this in the survival mode?

**Comment by lznEureka** [comment]
I noticed that in creation mode, I can freely tp in the nether to nether, nether to the overworld,  how do I configure this in the survival mode?

**Comment by LordDeatHunter** [comment]
You can teleport between dimensions in survival mode as well, you just need to have the required cost (items, xp, health, etc., whatever it is set to in configs)

**Comment by lznEureka** [comment]
emm,In the new world, I don't have a level of experience, so it is invalid, thank you
