### ISSUE TITLE
1.18.2 waystones , 3-4 spawn per village

### ISSUE THREAD

**Issue by TheRanker** [LordDeatHunter/FabricWaystones#98]
![image](https://user-images.githubusercontent.com/5889820/157326825-7e0cf06f-2070-4864-a3ea-6a10d9903caa.png)
so heres an image of a village on a newly generated world.. there are 4 waystones in this village... default config.. no changes at all.

{
  "worldgen": {
    "generate_in_villages": true,
    "village_waystone_weight": 5
  },
  "teleportation_cost": {
    "cost_type": "level",
    "cost_item": "minecraft:ender_pearl",
    "base_cost": 1,
    "cost_per_block_distance": 0.0,
    "cost_multiplier_between_dimensions": 1.0
  },
  "discover_with_item": "none",
  "take_amount_from_discover_item": 0,
  "consume_infinite_knowledge_scroll_on_use": false,
  "consume_local_void_on_use": true,
  "free_local_void_teleport": true,
  "store_waystone_data_on_sneak_break": true,
  "can_owners_redeem_payments": false,
  "waystone_block_hardness": 4.0,
  "waystone_block_required_mining_level": 1,
  "prevent_non_owners_from_breaking_waystone": false,
  "can_players_toggle_global_mode": true,
  "teleportation_cooldown": {
    "cooldown_ticks_when_hurt": 0,
    "cooldown_ticks_from_abyss_watcher": 0,
    "cooldown_ticks_from_pocket_wormhole": 0,
    "cooldown_ticks_from_local_void": 0,
    "cooldown_ticks_from_waystone": 0
  }
}

**Comment by LordDeatHunter** [comment]
I changed the way village generation works. For now, lower the "village_waystone_weight" value, in the future I might make it more configurable if I have time. If you (or anyone else) have a good suggestion for a good default weight, feel free to comment.
